"use client";

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  FileText, ShieldAlert, CheckSquare, Activity, 
  Download, ChevronRight, AlertTriangle, Scale,
  Calendar, DollarSign, FileCheck
} from 'lucide-react';

const MOCK_DATA = {
  health_score: 68,
  parties: ["Acme Corp (Vendor)", "TechNova Solutions (Client)"],
  values: {
    total: "$1,500,000",
    monthly: "$50,000"
  },
  risks: [
    { id: 1, clause: "Auto-Renewal Clause 5.2", severity: "CRITICAL", explanation: "Automatically renews for 3 years without prior notice." },
    { id: 2, clause: "Indemnification 8.1", severity: "High", explanation: "Uncapped liability for indirect damages." },
    { id: 3, clause: "Termination 9.4", severity: "Medium", explanation: "Vendor can terminate with 15 days notice." }
  ],
  obligations: [
    { id: 1, deadline: "2026-12-31", task: "Project Delivery Completion", completed: false },
    { id: 2, deadline: "2027-01-15", task: "Final Payment Milestone", completed: false },
    { id: 3, deadline: "Monthly", task: "99.9% Uptime Guarantee SLA", completed: true }
  ]
};

export default function ContractDashboard({ params }: { params: { id: string } }) {
  const [activeTab, setActiveTab] = useState<'summary' | 'risk' | 'obligations'>('risk');
  const hasCriticalRisk = MOCK_DATA.risks.some(r => r.severity === 'CRITICAL');

  const handleExport = () => {
    // Mock export functionality
    const element = document.createElement("a");
    const file = new Blob(["# Contract Analysis Report\n\nGenerated by AI SaaS Analyzer"], {type: 'text/markdown'});
    element.href = URL.createObjectURL(file);
    element.download = "contract-analysis-report.md";
    document.body.appendChild(element);
    element.click();
  };

  return (
    <div className="min-h-screen bg-[#050505] text-neutral-200 flex flex-col font-sans">
      {/* Top Action Bar */}
      <header className="h-16 border-b border-neutral-800 bg-[#0A0A0A] flex items-center justify-between px-6 sticky top-0 z-50">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <Scale className="w-5 h-5 text-emerald-500" />
            <h1 className="font-semibold text-lg text-white">MSA_AcmeCorp_v2.pdf</h1>
          </div>
          <span className="px-2.5 py-1 bg-neutral-800 text-neutral-400 text-xs rounded-md font-mono">ID: {params.id}</span>
        </div>
        
        <button 
          onClick={handleExport}
          className="flex items-center gap-2 px-4 py-2 bg-neutral-100 hover:bg-white text-black text-sm font-medium rounded-lg transition-colors"
        >
          <Download className="w-4 h-4" /> Export Report
        </button>
      </header>

      {/* Critical Alert Banner */}
      <AnimatePresence>
        {hasCriticalRisk && activeTab !== 'risk' && (
          <motion.div 
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="bg-red-500/10 border-b border-red-500/20 px-6 py-3 flex items-center justify-between"
          >
            <div className="flex items-center gap-3">
              <AlertTriangle className="w-5 h-5 text-red-500 animate-pulse" />
              <span className="text-sm font-medium text-red-200">
                CRITICAL risks detected in this contract requiring immediate attention.
              </span>
            </div>
            <button 
              onClick={() => setActiveTab('risk')}
              className="text-xs font-semibold text-red-400 hover:text-red-300 transition-colors uppercase tracking-wider"
            >
              View Risks &rarr;
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Split Layout */}
      <main className="flex-1 flex overflow-hidden">
        
        {/* Left Panel: Document Viewer */}
        <section className="w-1/2 border-r border-neutral-800 bg-neutral-900/20 relative flex flex-col">
          <div className="p-4 border-b border-neutral-800 bg-[#0A0A0A] flex items-center gap-2 text-sm text-neutral-400">
            <FileText className="w-4 h-4" /> Source Document Viewer
          </div>
          <div className="flex-1 p-8 overflow-y-auto">
            {/* Mock PDF Content */}
            <div className="max-w-xl mx-auto bg-white/5 p-8 rounded-xl border border-neutral-800 shadow-2xl backdrop-blur-sm min-h-[800px] text-neutral-300 text-sm leading-relaxed font-serif">
              <h2 className="text-2xl font-bold text-white mb-6 text-center">MASTER SERVICES AGREEMENT</h2>
              <p className="mb-4">This Master Services Agreement ("Agreement") is made effective as of the date of last signature...</p>
              
              <h3 className="text-lg font-bold text-white mt-8 mb-4">5. Term and Termination</h3>
              <p className="mb-4">5.1 Term. The initial term of this Agreement shall be for a period of one (1) year...</p>
              <div className="relative group cursor-pointer">
                <div className="absolute -inset-2 bg-red-500/10 border border-red-500/30 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity"></div>
                <p className="mb-4 relative z-10 px-2 py-1 bg-red-500/10 text-red-200 border-l-2 border-red-500">
                  <span className="font-bold">5.2 Auto-Renewal.</span> Unless either party provides written notice of termination at least ninety (90) days prior to the expiration of the current term, this Agreement shall automatically renew for successive periods of three (3) years under the same terms and conditions.
                </p>
              </div>

              <h3 className="text-lg font-bold text-white mt-8 mb-4">8. Indemnification and Liability</h3>
              <div className="relative group cursor-pointer mt-4">
                <p className="mb-4 relative z-10 px-2 py-1 bg-orange-500/10 text-orange-200 border-l-2 border-orange-500">
                  <span className="font-bold">8.1 Indemnification.</span> Vendor agrees to indemnify, defend, and hold harmless the Client from and against any and all claims, damages, liabilities, costs, and expenses arising out of indirect, incidental, or consequential damages...
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Right Panel: Analysis Tabs */}
        <section className="w-1/2 flex flex-col bg-[#050505]">
          <div className="flex border-b border-neutral-800">
            <TabButton 
              active={activeTab === 'summary'} 
              onClick={() => setActiveTab('summary')}
              icon={<Activity className="w-4 h-4" />}
              label="Executive Summary"
            />
            <TabButton 
              active={activeTab === 'risk'} 
              onClick={() => setActiveTab('risk')}
              icon={<ShieldAlert className="w-4 h-4" />}
              label="Risk Radar"
              hasAlert={hasCriticalRisk}
            />
            <TabButton 
              active={activeTab === 'obligations'} 
              onClick={() => setActiveTab('obligations')}
              icon={<CheckSquare className="w-4 h-4" />}
              label="Obligations"
            />
          </div>

          <div className="flex-1 overflow-y-auto p-6">
            <AnimatePresence mode="wait">
              
              {/* SUMMARY TAB */}
              {activeTab === 'summary' && (
                <motion.div 
                  key="summary"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="space-y-6"
                >
                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-[#0A0A0A] border border-neutral-800 p-6 rounded-2xl flex flex-col items-center justify-center text-center">
                      <div className="text-sm text-neutral-400 mb-2">Contract Health Score</div>
                      <div className="text-5xl font-bold text-emerald-400 tracking-tighter">
                        {MOCK_DATA.health_score}<span className="text-2xl text-neutral-600">/100</span>
                      </div>
                      <div className="mt-4 text-xs bg-emerald-500/10 text-emerald-400 px-3 py-1 rounded-full border border-emerald-500/20">
                        Needs Negotiation
                      </div>
                    </div>
                    
                    <div className="space-y-4">
                      <div className="bg-[#0A0A0A] border border-neutral-800 p-5 rounded-2xl">
                        <div className="flex items-center gap-2 text-sm text-neutral-400 mb-2">
                          <DollarSign className="w-4 h-4" /> Financials
                        </div>
                        <div className="text-lg font-semibold text-white">{MOCK_DATA.values.total} <span className="text-sm font-normal text-neutral-500">Total</span></div>
                        <div className="text-sm text-neutral-400 mt-1">{MOCK_DATA.values.monthly} / month</div>
                      </div>
                      <div className="bg-[#0A0A0A] border border-neutral-800 p-5 rounded-2xl">
                        <div className="flex items-center gap-2 text-sm text-neutral-400 mb-2">
                          <FileCheck className="w-4 h-4" /> Parties
                        </div>
                        {MOCK_DATA.parties.map(p => (
                          <div key={p} className="text-sm text-neutral-200 mt-1">{p}</div>
                        ))}
                      </div>
                    </div>
                  </div>
                </motion.div>
              )}

              {/* RISK RADAR TAB */}
              {activeTab === 'risk' && (
                <motion.div 
                  key="risk"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="space-y-4"
                >
                  {MOCK_DATA.risks.map((risk) => (
                    <div 
                      key={risk.id}
                      className={`p-5 rounded-2xl border ${
                        risk.severity === 'CRITICAL' 
                          ? 'bg-red-500/5 border-red-500/30' 
                          : risk.severity === 'High'
                          ? 'bg-orange-500/5 border-orange-500/20'
                          : 'bg-neutral-900 border-neutral-800'
                      }`}
                    >
                      <div className="flex justify-between items-start mb-3">
                        <h4 className="font-semibold text-white">{risk.clause}</h4>
                        <span className={`text-xs px-2.5 py-1 rounded-full font-medium ${
                          risk.severity === 'CRITICAL' ? 'bg-red-500 text-white shadow-[0_0_15px_rgba(239,68,68,0.5)] animate-pulse' :
                          risk.severity === 'High' ? 'bg-orange-500/20 text-orange-400 border border-orange-500/30' :
                          'bg-neutral-800 text-neutral-300'
                        }`}>
                          {risk.severity}
                        </span>
                      </div>
                      <p className="text-sm text-neutral-400 mb-4">{risk.explanation}</p>
                      
                      {risk.severity === 'CRITICAL' && (
                        <div className="mt-4 p-4 bg-[#050505] rounded-xl border border-neutral-800/50">
                          <div className="text-xs text-neutral-500 uppercase tracking-wider mb-2 font-semibold">AI Negotiator Suggestion</div>
                          <p className="text-sm text-emerald-400/90 font-mono">
                            <span className="text-neutral-500 line-through mr-2">automatically renews for successive periods of three (3) years</span>
                            <br/>
                            "Agreement may be renewed upon mutual written consent 30 days prior to expiration."
                          </p>
                        </div>
                      )}
                    </div>
                  ))}
                </motion.div>
              )}

              {/* OBLIGATIONS TAB */}
              {activeTab === 'obligations' && (
                <motion.div 
                  key="obligations"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="space-y-3"
                >
                  {MOCK_DATA.obligations.map((ob) => (
                    <div key={ob.id} className="flex items-center gap-4 p-4 bg-[#0A0A0A] border border-neutral-800 rounded-xl hover:border-neutral-700 transition-colors group">
                      <button className={`w-5 h-5 rounded flex items-center justify-center border ${ob.completed ? 'bg-emerald-500 border-emerald-500 text-[#050505]' : 'border-neutral-600 group-hover:border-neutral-500'}`}>
                        {ob.completed && <CheckSquare className="w-3 h-3" />}
                      </button>
                      <div className="flex-1">
                        <div className={`text-sm ${ob.completed ? 'text-neutral-500 line-through' : 'text-neutral-200'}`}>{ob.task}</div>
                      </div>
                      <div className="flex items-center gap-1.5 text-xs text-neutral-500 bg-neutral-900 px-2.5 py-1 rounded-md border border-neutral-800">
                        <Calendar className="w-3 h-3" />
                        {ob.deadline}
                      </div>
                    </div>
                  ))}
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </section>

      </main>
    </div>
  );
}

function TabButton({ active, onClick, icon, label, hasAlert }: any) {
  return (
    <button
      onClick={onClick}
      className={`flex-1 flex items-center justify-center gap-2 py-4 px-6 text-sm font-medium transition-all relative
        ${active ? 'text-white' : 'text-neutral-500 hover:text-neutral-300 hover:bg-neutral-900/50'}
      `}
    >
      {icon}
      {label}
      {hasAlert && !active && (
        <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse absolute top-4 right-1/4"></span>
      )}
      {active && (
        <motion.div 
          layoutId="tab-indicator"
          className="absolute bottom-0 left-0 right-0 h-0.5 bg-emerald-500"
        />
      )}
    </button>
  );
}
