'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Role = 'Evaluator' | 'Director';
export type PortalType = 'gov' | 'corp';
export type Language = 'EN' | 'HI' | 'BN' | 'TE' | 'MR' | 'TA' | 'GU' | 'KN' | 'ML' | 'PA';

interface AppContextType {
  role: Role;
  setRole: (role: Role) => void;
  portalType: PortalType;
  setPortalType: (portal: PortalType) => void;
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    // Sidebar
    'nav_dashboard': 'Cryptographic Ledger',
    'nav_criteria_setup': 'Tender DNA Compiler',
    'nav_evaluation_matrix': 'Immutable Audit Interface',
    'nav_draft_analyzer': 'Logic-Gate Draft Compiler',
    'nav_audit_trail': 'Statutory Audit Trail',
    'nav_settings': 'Settings',
    'nav_rti_management': 'RTI Management',
    
    // Dashboard
    'program_dashboard': 'Cryptographic Maker-Checker Ledger',
    'overview_description': 'Immutable ledger for statutory procurement and zero-trust entity verification.',
    'total_bidders': 'Total Entities',
    'cleared': 'Verified',
    'rejected': 'Failed Verification',
    'review': 'Needs Review',
    'active_tenders': 'Active DNA Projects',
    'new_tender': 'New DNA Compiler',
    'analytics': 'Collusion Topology',
    'bidder_intelligence_matrix': 'Cryptographic Maker-Checker Ledger',
    'live_ai_stream': 'Real-Time DNA Compiler Stream',
    'thinking': 'Executing Logic-Gates...',
    'analyze_precedents': 'Analyze GFR Defensibility',
    'export_results': 'Export Ledger',
    'confirm_selection': 'Confirm GFR Compliance',
    'officer_smith': 'Officer Smith',
    'crpf_division': 'CRPF Division',
    'current_role': 'Current Role',
    'junior_evaluator': 'Maker (Junior Evaluator)',
    'procurement_director': 'Checker (Director)',
    'select_access': 'Select Access Level',
    'system_alert_rate_limit': 'System Alert: GFR Defensibility Engine switching to Local Secure Cache.',
    
    // Criteria
    'crit_turnover': 'Minimum Annual Turnover',
    'crit_projects': 'Similar Projects',
    'crit_gst': 'GST Registration',
    'crit_iso': 'ISO Certification',
    'active': 'Active',
    'view': 'View',
    'statutory_agent': 'Statutory Agent',
    'powered_by_gfr': 'Powered by GFR Defensibility Engine',
    'agent_summary': "I've executed logic-gates for all 10 bidder submissions for the CRPF tender. All submissions have been processed and recorded in the secure ledger.",
    'gen_audit_report': 'Generate Audit Report',
    'active_tenders_desc': 'Live evaluation processes currently in the system.',
  },
  HI: {
    // Sidebar
    'nav_dashboard': 'क्रिप्टोग्राफिक लेजर',
    'nav_criteria_setup': 'टेंडर DNA कंपाइलर',
    'nav_evaluation_matrix': 'इम्यूटेबल ऑडिट इंटरफ़ेस',
    'nav_draft_analyzer': 'लॉजिक-गेट ड्राफ्ट कंपाइलर',
    'nav_audit_trail': 'वैधानिक ऑडिट ट्रेल',
    'nav_settings': 'सेटिंग्स',
    'nav_rti_management': 'RTI प्रबंधन',
    
    // Dashboard & Headers
    'program_dashboard': 'क्रिप्टोग्राफिक मेकर-चेकर लेजर',
    'overview_description': 'वैधानिक खरीद और शून्य-विश्वास इकाई सत्यापन के लिए इम्यूटेबल लेजर।',
    'total_bidders': 'कुल संस्थाएं',
    'cleared': 'सत्यापित',
    'rejected': 'सत्यापन विफल',
    'active_tenders': 'सक्रिय DNA प्रोजेक्ट्स',
    'new_tender': 'नया DNA कंपाइलर',
    'analytics': 'मिलीभगत टोपोलॉजी',
    'bidder_intelligence_matrix': 'बोलीदाता इंटेलिजेंस मैट्रिक्स',
    'live_ai_stream': 'लाइव एआई ऑडिट टनल',
    'thinking': 'लॉजिक-गेट्स निष्पादित हो रहे हैं...',
    'analyze_precedents': 'GFR बचाव का विश्लेषण करें',
    'export_results': 'लेजर निर्यात करें',
    'confirm_selection': 'चयन की पुष्टि करें',
    'officer_smith': 'अधिकारी स्मिथ',
    'crpf_division': 'सीआरपीएफ डिवीजन',
    'current_role': 'वर्तमान भूमिका',
    'junior_evaluator': 'मेकर (कनिष्ठ मूल्यांकनकर्ता)',
    'procurement_director': 'चेकर (निदेशक)',
    'select_access': 'पहुँच स्तर चुनें',
    'system_alert_rate_limit': 'सिस्टम अलर्ट: GFR बचाव इंजन स्थानीय सुरक्षित कैश पर स्विच कर रहा है।',

    // Evaluation Matrix Specifics
    'tenders': 'निविदाएं',
    'zero_trust_mode': 'शून्य-विश्वास सत्यापन मोड',
    'compare_selected': 'चयनित तुलना करें',
    'sign_and_lock': 'डिजिटल रूप से साइन और लॉक करें',
    'checker_ledger': 'चेकर वैधानिक लेजर',
    'checker_mode_active': 'वैधानिक चेकर मोड सक्रिय। तकनीकी पुरस्कार को अंतिम रूप देने के लिए आपके डिजिटल हस्ताक्षर आवश्यक हैं।',
    'passes_verified': 'तकनीकी पास सत्यापित',
    'ask_ai_placeholder': 'पिछले टेंडर फैसलों के बारे में एआई से पूछें...',
    'statutory_gfr_insight': 'वैधानिक GFR अंतर्दृष्टि',
    'dna_centric': 'DNA-केंद्रित',
    'search_bidders': 'बोलीदाताओं की खोज करें...',
    'filter': 'फ़िल्टर',
    'filter_by_status': 'स्थिति के अनुसार फ़िल्टर करें',
    'clear_all': 'सभी साफ़ करें',
    'pass': 'पास',
    'fail': 'विफल',
    'bidder_name': 'बोलीदाता का नाम',
    'mandatory': 'अनिवार्य',
    'optional': 'वैयक्तिक',
    'collusion_index': 'मिलीभगत सूचकांक',
    'analysis_actions': 'विश्लेषण और क्रियाएं',
    'overall_status': 'कुल मिलाकर स्थिति',
    'live_dna_stream': 'लाइव DNA स्ट्रीम',
    'processing_live': '[नया: लाइव स्ट्रीम प्रोसेसिंग]',
    'verified': '[सत्यापित]',
    'evaluating': 'मूल्यांकन जारी',
    'ready_for_award': 'पुरस्कार के लिए तैयार',
    'gen_rejection_notice': 'अस्वीकृति सूचना उत्पन्न करें',
    'verified_network': 'सत्यापित नेटवर्क',
    'anomaly_detected': 'विसंगति पाई गई',
    'collusion_alert': 'मिलीभगत अलर्ट',
    'gfr_defensibility_index': 'GFR बचाव सूचकांक',
    'no_anomalies': 'एआई द्वारा कोई महत्वपूर्ण विसंगति नहीं पाई गई।',
    'translated': 'अनूदित',
    'critical_anomaly': 'गंभीर विसंगति',
    'active': 'सक्रिय',
    'view': 'देखें',
    'statutory_agent': 'वैधानिक एजेंट',
    'powered_by_gfr': 'GFR बचाव इंजन द्वारा संचालित',
    'agent_summary': 'मैंने CRPF टेंडर के लिए सभी 10 बोलीदाता सबमिशन के लिए लॉजिक-गेट्स निष्पादित किए हैं। सभी सबमिशन संसाधित किए गए हैं और सुरक्षित लेज़र में दर्ज किए गए हैं।',
    'gen_audit_report': 'ऑडिट रिपोर्ट उत्पन्न करें',
    'active_tenders_desc': 'सिस्टम में वर्तमान में लाइव मूल्यांकन प्रक्रियाएं।',

    // Dynamic Categories
    'financial': 'वित्तीय',
    'technical': 'तकनीकी',
    'statutory': 'वैधानिक',

    // Criteria
    'crit_turnover': 'न्यूनतम वार्षिक कारोबार',
    'crit_projects': 'समान परियोजनाएं',
    'crit_gst': 'GST पंजीकरण',
    'crit_iso': 'ISO प्रमाणन',
  },
  BN: {
    'nav_dashboard': 'ড্যাশবোর্ড',
    'nav_criteria_setup': 'মাপদণ্ড সেটআপ',
    'nav_evaluation_matrix': 'মূল্যায়ন ম্যাট্রিক্স',
    'nav_draft_analyzer': 'ড্রাফ্ট বিশ্লেষক',
    'nav_audit_trail': 'অডিট ট্রেইল',
    'nav_settings': 'সেটিংস',
    'nav_rti_management': 'RTI ম্যানেজমেন্ট',
    'program_dashboard': 'প্রোগ্রাম ড্যাশবোর্ড',
    'overview_description': 'সংগ্রহ কার্যক্রম এবং সক্রিয় দরপত্রের ওভারভিউ।',
    'total_bidders': 'মোট দরদাতা',
    'cleared': 'ক্লিয়ার করা হয়েছে',
    'rejected': 'প্রত্যাখ্যাত',
    'active_tenders': 'সক্রিয় দরপত্র',
    'new_tender': 'নতুন দরপত্র',
    'analytics': 'বিশ্লেষণ',
    'bidder_intelligence_matrix': 'বিডার ইন্টেলিজেন্স ম্যাট্রিক্স',
    'live_ai_stream': 'লাইভ এআই মূল্যায়ন স্ট্রীম',
    'thinking': 'চিন্তা করছি...',
    'analyze_precedents': 'নজির বিশ্লেষণ',
    'export_results': 'ফলাফল রপ্তানি করুন',
    'confirm_selection': 'নিশ্চিত করুন',
    'officer_smith': 'অফিসার স্মিথ',
    'crpf_division': 'সিআরপিএফ বিভাগ',
    'current_role': 'বর্তমান ভূমিকা',
    'junior_evaluator': 'জুনিয়র মূল্যায়নকারী',
    'procurement_director': 'সংগ্রহ পরিচালক',
    'select_access': 'অ্যাক্সেস লেভেল নির্বাচন করুন',
    'system_alert_rate_limit': 'সিস্টেম অ্যালার্ট: API রেট লিমিট শেষ। লোকাল ক্যাশে স্যুইচ করা হচ্ছে।',
  },
  TE: {
    'nav_dashboard': 'డాష్‌బోర్డ్',
    'nav_criteria_setup': 'ప్రమాణాల సెటప్',
    'nav_evaluation_matrix': 'మూల్యాంకన మ్యాట్రిక్స్',
    'nav_draft_analyzer': 'డ్రాఫ్ట్ అనలైజర్',
    'nav_audit_trail': 'ఆడిట్ ట్రయల్',
    'nav_settings': 'సెట్టింగులు',
    'nav_rti_management': 'RTI నిర్వహణ',
    'program_dashboard': 'ప్రోగ్రామ్ డాష్‌బోర్డ్',
    'overview_description': 'కొనుగోలు కార్యకలాపాలు మరియు క్రియాశీల టెండర్ల అవలోకనం.',
    'total_bidders': 'మొత్తం బిడ్డర్లు',
    'cleared': 'క్లియర్ చేయబడింది',
    'rejected': 'తిరస్కరించబడింది',
    'active_tenders': 'క్రియాశీల టెండర్లు',
    'new_tender': 'కొత్త టెండర్',
    'analytics': 'విశ్లేషణలు',
    'bidder_intelligence_matrix': 'బిడ్డర్ ఇంటెలిజెన్స్ మ్యాట్రిక్స్',
    'live_ai_stream': 'లైవ్ AI మూల్యాంకన స్ట్రీమ్',
    'thinking': 'ఆలోచిస్తున్నాను...',
    'analyze_precedents': 'పూర్వాపరాల విశ్లేషణ',
    'export_results': 'ఫలితాలను ఎగుమతి చేయండి',
    'confirm_selection': 'ఎంపికను నిర్ధారించండి',
    'officer_smith': 'ఆఫీసర్ స్మిత్',
    'crpf_division': 'CRPF డివిజన్',
    'current_role': 'ప్రస్తుత పాత్ర',
    'junior_evaluator': 'జూనియర్ ఎవాల్యుయేటర్',
    'procurement_director': 'ప్రొక్యూర్‌మెంట్ డైరెక్టర్',
    'select_access': 'యాక్సెస్ స్థాయిని ఎంచుకోండి',
    'system_alert_rate_limit': 'సిస్టమ్ అలర్ట్: API రేట్ లిమిట్ మించిపోయింది. లోకల్ కాష్‌కు మారుతోంది।',
  },
  MR: {
    'nav_dashboard': 'डॅशबोर्ड',
    'nav_criteria_setup': 'निकष सेटअप',
    'nav_evaluation_matrix': 'मूल्यमापन मॅट्रिक्स',
    'nav_draft_analyzer': 'मसुदा विश्लेषक',
    'nav_audit_trail': 'ऑडिट ट्रेल',
    'nav_settings': 'सेटिंग्स',
    'nav_rti_management': 'RTI व्यवस्थापन',
    'program_dashboard': 'कार्यक्रम डॅशबोर्ड',
    'overview_description': 'खरेदी उपक्रम आणि सक्रिय निविदांचे विहंगावलोकन.',
    'total_bidders': 'एकूण बोलीदार',
    'cleared': 'मंजूर',
    'rejected': 'नाकारले',
    'active_tenders': 'सक्रिय निविदा',
    'new_tender': 'नवीन निविदा',
    'analytics': 'विश्लेषण',
    'bidder_intelligence_matrix': 'बोलीदार इंटेलिजन्स मॅट्रिक्स',
    'live_ai_stream': 'लाइव्ह एआय मूल्यमापन प्रवाह',
    'thinking': 'विचार करत आहे...',
    'analyze_precedents': 'नमुन्यांचे विश्लेषण',
    'export_results': 'निकाल निर्यात करा',
    'confirm_selection': 'निवडीची पुष्टी करा',
    'officer_smith': 'अधिकारी स्मिथ',
    'crpf_division': 'सीआरपीएफ विभाग',
    'current_role': 'सध्याची भूमिका',
    'junior_evaluator': 'कनिष्ठ मूल्यमापक',
    'procurement_director': 'खरेदी संचालक',
    'select_access': 'प्रवेश स्तर निवडा',
    'system_alert_rate_limit': 'सिस्टम अलर्ट: API मर्यादा संपली. स्थानिक कॅशेवर स्विच करत आहे।',
  },
  TA: {
    'nav_dashboard': 'டாஷ்போர்டு',
    'nav_criteria_setup': 'நிபந்தனைகள் அமைப்பு',
    'nav_evaluation_matrix': 'மதிப்பீட்டு அணி',
    'nav_draft_analyzer': 'வரைவு பகுப்பாய்வி',
    'nav_audit_trail': 'தணிக்கை பாதை',
    'nav_settings': 'அமைப்புகள்',
    'nav_rti_management': 'RTI மேலாண்மை',
    'program_dashboard': 'நிரல் டாஷ்போர்டு',
    'overview_description': 'கொள்முதல் நடவடிக்கைகள் மற்றும் செயலில் உள்ள டெண்டர்களின் மேலோட்டம்.',
    'total_bidders': 'மொத்த ஏலதாரர்கள்',
    'cleared': 'அங்கீகரிக்கப்பட்டது',
    'rejected': 'நிராகரிக்கப்பட்டது',
    'active_tenders': 'செயலில் உள்ள டெண்டர்கள்',
    'new_tender': 'புதிய டெண்டர்',
    'analytics': 'பகுப்பாய்வு',
    'bidder_intelligence_matrix': 'ஏலதாரர் நுண்ணறிவு அணி',
    'live_ai_stream': 'நேரடி AI மதிப்பீட்டு ஓட்டம்',
    'thinking': 'யோசிக்கிறது...',
    'analyze_precedents': 'முன்னுதாரணங்களை ஆய்வு செய்யுங்கள்',
    'export_results': 'முடிவுகளை ஏற்றுமதி செய்',
    'confirm_selection': 'தேர்வை உறுதிப்படுத்து',
    'officer_smith': 'அதிகாரி ஸ்மித்',
    'crpf_division': 'CRPF பிரிவு',
    'current_role': 'தற்போதைய பொறுப்பு',
    'junior_evaluator': 'இளநிலை மதிப்பீட்டாளர்',
    'procurement_director': 'கொள்முதல் இயக்குனர்',
    'select_access': 'அணுகல் நிலையைத் தேர்ந்தெடுக்கவும்',
    'system_alert_rate_limit': 'கணினி எச்சரிக்கை: API வரம்பு முடிந்தது. உள்ளூர் தற்காலிக சேமிப்பிற்கு மாறுகிறது।',
  },
  GU: {
    'nav_dashboard': 'ડેશબોર્ડ',
    'nav_criteria_setup': 'માપદંડ સેટઅપ',
    'nav_evaluation_matrix': 'મૂલ્યાંકન મેટ્રિક્સ',
    'nav_draft_analyzer': 'ડ્રાફ્ટ વિશ્લેષક',
    'nav_audit_trail': 'ઓડિટ ટ્રેઇલ',
    'nav_settings': 'સેટિંગ્સ',
    'nav_rti_management': 'RTI મેનેજમેન્ટ',
    'program_dashboard': 'પ્રોગ્રામ ડેશબોર્ડ',
    'overview_description': 'ખરીદી પ્રવૃત્તિઓ અને સક્રિય ટેન્ડરોની ઝાંખી.',
    'total_bidders': 'કુલ બિડર્સ',
    'cleared': 'મંજૂર',
    'rejected': 'અસ્વીકાર્ય',
    'active_tenders': 'સક્રિય ટેન્ડરો',
    'new_tender': 'નવું ટેન્ડર',
    'analytics': 'વિશ્લેષણ',
    'bidder_intelligence_matrix': 'બિડર ઇન્ટેલિજન્સ મેટ્રિક્સ',
    'live_ai_stream': 'લાઇવ AI મૂલ્યાંકન સ્ટ્રીમ',
    'thinking': 'વિચારી રહ્યું છે...',
    'analyze_precedents': 'પૂર્વધારણા વિશ્લેષણ',
    'export_results': 'પરિણામો નિકાસ કરો',
    'confirm_selection': 'પસંદગીની પુષ્ટિ કરો',
    'officer_smith': 'ઓફિસર સ્મિથ',
    'crpf_division': 'CRPF વિભાગ',
    'current_role': 'વર્તમાન ભૂમિકા',
    'junior_evaluator': 'જુનિયર મૂલ્યાંકનકાર',
    'procurement_director': 'ખરીદી નિયામક',
    'select_access': 'એક્સેસ લેવલ પસંદ કરો',
    'system_alert_rate_limit': 'સિસ્ટમ એલર્ટ: API મર્યાદા પૂરી થઈ. સ્થાનિક કેશ પર સ્વિચ કરી રહ્યું છે।',
  },
  KN: {
    'nav_dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav_criteria_setup': 'ಮಾನದಂಡಗಳ ಸೆಟಪ್',
    'nav_evaluation_matrix': 'ಮೌಲ್ಯಮಾಪನ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    'nav_draft_analyzer': 'ಕರಡು ವಿಶ್ಲೇಷಕ',
    'nav_audit_trail': 'ಆಡಿಟ್ ಟ್ರಯಲ್',
    'nav_settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav_rti_management': 'RTI ನಿರ್ವಹಣೆ',
    'program_dashboard': 'ಕಾರ್ಯಕ್ರಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'overview_description': 'ಖರೀದಿ ಚಟುವಟಿಕೆಗಳು ಮತ್ತು ಸಕ್ರಿಯ ಟೆಂಡರ್‌ಗಳ ಅವಲೋಕನ.',
    'total_bidders': 'ಒಟ್ಟು ಬಿಡ್ದಾರರು',
    'cleared': 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    'rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    'active_tenders': 'ಸಕ್ರಿಯ ಟೆಂಡರ್‌ಗಳು',
    'new_tender': 'ಹೊಸ ಟೆಂಡರ್',
    'analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'bidder_intelligence_matrix': 'ಬಿಡ್ದಾರರ ಇಂಟೆಲಿಜೆನ್ಸ್ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    'live_ai_stream': 'ಲೈವ್ AI ಮೌಲ್ಯಮಾಪನ ಸ್ಟ್ರೀಮ್',
    'thinking': 'ಯೋಚಿಸುತ್ತಿದೆ...',
    'analyze_precedents': 'ಪೂರ್ವಾಪರಗಳ ವಿಶ್ಲೇಷಣೆ',
    'export_results': 'ಫಲಿತಾಂಶಗಳನ್ನು ರಫ್ತು ಮಾಡಿ',
    'confirm_selection': 'ಆಯ್ಕೆಯನ್ನು ಖಚಿತಪಡಿಸಿ',
    'officer_smith': 'ಆಫೀಸರ್ ಸ್ಮಿತ್',
    'crpf_division': 'CRPF ವಿಭಾಗ',
    'current_role': 'ಪ್ರಸ್ತುತ ಪಾತ್ರ',
    'junior_evaluator': 'ಕಿರಿಯ ಮೌಲ್ಯಮಾಪಕ',
    'procurement_director': 'ಖರೀದಿ ನಿರ್ದೇಶಕ',
    'select_access': 'ಪ್ರವೇಶ ಮಟ್ಟವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'system_alert_rate_limit': 'ಸಿಸ್ಟಮ್ ಅಲರ್ಟ್: API ಮಿತಿ ಮೀರಿದೆ. ಸ್ಥಳೀಯ ಕ್ಯಾಶ್‌ಗೆ ಬದಲಾಯಿಸಲಾಗುತ್ತಿದೆ।',
  },
  ML: {
    'nav_dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav_criteria_setup': 'മാനദണ്ഡ സജ്ജീകരണം',
    'nav_evaluation_matrix': 'മൂല്യനിർണ്ണയ മാട്രിക്സ്',
    'nav_draft_analyzer': 'ഡ്രാഫ്റ്റ് അനലൈസർ',
    'nav_audit_trail': 'ഓഡിറ്റ് ട്രയൽ',
    'nav_settings': 'ക്രമീകരണങ്ങൾ',
    'nav_rti_management': 'RTI മാനേജ്‌മെന്റ്',
    'program_dashboard': 'പ്രോഗ്രാം ഡാഷ്‌ബോർഡ്',
    'overview_description': 'പർച്ചേസ് പ്രവർത്തനങ്ങളുടെയും സജീവ ടെണ്ടറുകളുടെയും അവലോകനം.',
    'total_bidders': 'ആകെ ബിഡ്ഡറുകൾ',
    'cleared': 'അംഗീകരിച്ചു',
    'rejected': 'നിരസിച്ചു',
    'active_tenders': 'സജീവ ടെണ്ടറുകൾ',
    'new_tender': 'പുതിയ ടെണ്ടർ',
    'analytics': 'അനലിറ്റിക്സ്',
    'bidder_intelligence_matrix': 'ബിഡ്ഡർ ഇൻ്റലിജൻസ് മാട്രിക്സ്',
    'live_ai_stream': 'ലൈവ് AI മൂല്യനിർണ്ണയ സ്ട്രീം',
    'thinking': 'ചിന്തിക്കുന്നു...',
    'analyze_precedents': 'മുൻഗണനാ വിശകലനം',
    'export_results': 'ഫലങ്ങൾ കയറ്റുമതി ചെയ്യുക',
    'confirm_selection': 'തിരഞ്ഞെടുക്കൽ സ്ഥിരീകരിക്കുക',
    'officer_smith': 'ഓഫീസർ സ്മിത്ത്',
    'crpf_division': 'CRPF ഡിവിഷൻ',
    'current_role': 'നിലവിലെ റോൾ',
    'junior_evaluator': 'ജൂനിയർ ഇവാലുവേറ്റർ',
    'procurement_director': 'പ്രൊക്യുർമെൻ്റ് ഡയറക്ടർ',
    'select_access': 'ആക്സസ് ലെവൽ തിരഞ്ഞെടുക്കുക',
    'system_alert_rate_limit': 'സിസ്റ്റം അലർട്ട്: API പരിധി കഴിഞ്ഞു. ലോക്കൽ കാഷെയിലേക്ക് മാറുന്നു।',
  },
  PA: {
    'nav_dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav_criteria_setup': 'ਮਾਪਦੰਡ ਸੈੱਟਅੱਪ',
    'nav_evaluation_matrix': 'ਮੁਲਾਂਕਣ ਮੈਟਰਿਕਸ',
    'nav_draft_analyzer': 'ਡਰਾਫਟ ਵਿਸ਼ਲੇਸ਼ਕ',
    'nav_audit_trail': 'ਆਡਿਟ ਟ੍ਰੇਲ',
    'nav_settings': 'ਸੈਟਿੰਗਾਂ',
    'nav_rti_management': 'RTI ਪ੍ਰਬੰਧਨ',
    'program_dashboard': 'ਪ੍ਰੋਗਰਾਮ ਡੈਸ਼ਬੋਰਡ',
    'overview_description': 'ਖਰੀਦ ਗਤੀਵਿਧੀਆਂ ਅਤੇ ਸਰਗਰਮ ਟੈਂਡਰਾਂ ਦਾ ਵੇਰਵਾ।',
    'total_bidders': 'ਕੁੱਲ ਬੋਲੀਕਾਰ',
    'cleared': 'ਪਾਸ ਕੀਤਾ ਗਿਆ',
    'rejected': 'ਰੱਦ ਕੀਤਾ ਗਿਆ',
    'active_tenders': 'ਸਰਗਰਮ ਟੈਂਡਰ',
    'new_tender': 'ਨਵਾਂ ਟੈਂਡਰ',
    'analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'bidder_intelligence_matrix': 'ਬੋਲੀਕਾਰ ਇੰਟੈਲੀਜੈਂਸ ਮੈਟਰਿਕਸ',
    'live_ai_stream': 'ਲਾਈਵ AI ਮੁਲਾਂਕਣ ਸਟ੍ਰੀਮ',
    'thinking': 'ਸੋਚ ਰਿਹਾ ਹੈ...',
    'analyze_precedents': 'ਮਿਸਾਲਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ',
    'export_results': 'ਨਤੀਜੇ ਨਿਰਯਾਤ ਕਰੋ',
    'confirm_selection': 'ਚੋਣ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'officer_smith': 'ਅਫਸਰ ਸਮਿਥ',
    'crpf_division': 'CRPF ਡਿਵੀਜ਼ਨ',
    'current_role': 'ਮੌਜੂਦਾ ਭੂਮਿਕਾ',
    'junior_evaluator': 'ਜੂਨੀਅਰ ਮੁਲਾਂਕਣਕਾਰ',
    'procurement_director': 'ਖਰੀਦ ਨਿਰਦੇਸ਼ਕ',
    'select_access': 'ਪਹੁੰਚ ਪੱਧਰ ਚੁਣੋ',
    'system_alert_rate_limit': 'ਸਿਸਟਮ ਅਲਰਟ: API ਸੀਮਾ ਖਤਮ। ਲੋਕਲ ਕੈਸ਼ ਤੇ ਸਵਿਚ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ।',
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: ReactNode }) {
  const [role, setRole] = useState<Role>('Evaluator');
  const [portalType, setPortalType] = useState<PortalType>('gov');
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string) => {
    const dict = translations[language] as Record<string, string>;
    const fallback = translations.EN as Record<string, string>;
    return dict[key] || fallback[key] || key;
  };

  return (
    <AppContext.Provider value={{ role, setRole, portalType, setPortalType, language, setLanguage, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useAppContext() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useAppContext must be used within an AppProvider');
  }
  return context;
}

// Compatibility exports for existing code
export const useRole = () => {
  const { role, setRole } = useAppContext();
  return { role, setRole };
};
